# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chickenapptt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://chickenapptt.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a7acfcdcbe0e477f992c08e309cd32af }}
        password: ${{ secrets.AzureAppService_ContainerPassword_56b4fa5462be4f31984288647aa93256 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: chickenapptt.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a7acfcdcbe0e477f992c08e309cd32af }}/chicken:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chickenapptt'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_960889a984c44cecadbe2be58a7f3d5b }}
        images: 'chickenapptt.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a7acfcdcbe0e477f992c08e309cd32af }}/chicken:${{ github.sha }}'